source 'https://rubygems.org'

gem 'sinatra',         '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'sqlite3',         '~> 2.0'
gem 'puma',            '~> 6.0'

group :test do
  gem 'rspec',     '~> 3.13'
  gem 'rack-test', '~> 2.1'
end
